// Heatmap mode definitions and metadata
export const HEATMAP_MODES = {
  OFF: 'off',
  PORTFOLIO_WEIGHT: 'portfolio_weight',
  ACCOUNT_WEIGHT: 'account_weight',
  DAILY_PNL_AMOUNT: 'daily_pnl_amount',
  DAILY_PNL_PERCENT: 'daily_pnl_percent',
  UNREALIZED_GAIN_AMOUNT: 'unrealized_gain_amount',
  UNREALIZED_GAIN_PERCENT: 'unrealized_gain_percent',
  REALIZED_GAIN_AMOUNT: 'realized_gain_amount',
  REALIZED_GAIN_PERCENT: 'realized_gain_percent',
  REALIZED_GAIN_CONTRIBUTION: 'realized_gain_contribution',
  TOTAL_RETURN: 'total_return',
  PRICE_MOVEMENT: 'price_movement',
  VOLATILITY: 'volatility',
  CUSTOM_RISK: 'custom_risk',
};

export const HEATMAP_MODE_CONFIG = {
  [HEATMAP_MODES.OFF]: {
    label: 'Off',
    description: 'No heatmap coloring',
    category: 'visibility',
    legendText: 'Heatmap off.',
  },
  [HEATMAP_MODES.PORTFOLIO_WEIGHT]: {
   label: 'Portfolio Weight',
   description: 'Subtle color hints by portfolio %',
   category: 'concentration',
   legendText: 'Subtle amber tint hints at larger positions. Heatmap is intentionally subdued to preserve readability.',
   colorScheme: 'concentration',
  },
  [HEATMAP_MODES.ACCOUNT_WEIGHT]: {
   label: 'Account Weight',
   description: 'Subtle color hints by account %',
   category: 'concentration',
   legendText: 'Subtle amber tint hints at larger positions within each account. Prioritizes readability.',
   colorScheme: 'concentration',
  },
  [HEATMAP_MODES.DAILY_PNL_AMOUNT]: {
   label: 'Daily P&L $',
   description: 'Subtle hints by daily P&L amount',
   category: 'pnl',
   legendText: 'Subtle green tint for gains, red tint for losses. Very muted to keep text fully readable.',
   colorScheme: 'pnl',
  },
  [HEATMAP_MODES.DAILY_PNL_PERCENT]: {
   label: 'Daily P&L %',
   description: 'Subtle hints by daily P&L %',
   category: 'pnl',
   legendText: 'Subtle green tint for gains, red tint for losses. Heatmap is barely visible but helpful.',
   colorScheme: 'pnl',
  },
  [HEATMAP_MODES.UNREALIZED_GAIN_AMOUNT]: {
   label: 'Unrealized Gain $',
   description: 'Subtle hints by unrealized gain amount',
   category: 'returns',
   legendText: 'Very subtle green for winners, red for losers. Designed to guide without overwhelming.',
   colorScheme: 'pnl',
  },
  [HEATMAP_MODES.UNREALIZED_GAIN_PERCENT]: {
   label: 'Unrealized Gain %',
   description: 'Subtle hints by unrealized gain %',
   category: 'returns',
   legendText: 'Very subtle green for winners, red for losers. Readability is always the priority.',
   colorScheme: 'pnl',
  },
  [HEATMAP_MODES.REALIZED_GAIN_AMOUNT]: {
   label: 'Realized Gain $',
   description: 'Subtle hints by realized gain amount',
   category: 'returns',
   legendText: 'Very subtle green for gains, red for losses. Heatmap remains barely perceptible.',
   colorScheme: 'pnl',
  },
  [HEATMAP_MODES.REALIZED_GAIN_PERCENT]: {
   label: 'Realized Gain %',
   description: 'Subtle hints by realized gain %',
   category: 'returns',
   legendText: 'Very subtle green for gains, red for losses. Preserves clean table appearance.',
   colorScheme: 'pnl',
  },
  [HEATMAP_MODES.REALIZED_GAIN_CONTRIBUTION]: {
   label: 'Realized Gain Contribution %',
   description: 'Shows contribution to total realized gains/losses',
   category: 'returns',
   legendText: 'Green for positive contributors to realized gains, red for contributors to realized losses. Shows how much each stock contributed to total realized P&L.',
   colorScheme: 'pnl',
  },
  [HEATMAP_MODES.TOTAL_RETURN]: {
   label: 'Total Return',
   description: 'Subtle hints by total return',
   category: 'returns',
   legendText: 'Subtle green for total winners, red for total losers. All values remain perfectly readable.',
   colorScheme: 'pnl',
  },
  [HEATMAP_MODES.PRICE_MOVEMENT]: {
   label: 'Price Movement',
   description: 'Subtle hints by recent price movement',
   category: 'returns',
   legendText: 'Green for upward movement, red for downward. Based on recent intraday price changes.',
   colorScheme: 'pnl',
  },
  [HEATMAP_MODES.VOLATILITY]: {
   label: 'Volatility',
   description: 'Subtle hints by volatility level',
   category: 'risk',
   legendText: 'Very subtle orange tint for higher volatility. Gentle visual cue, not an alarm.',
   colorScheme: 'volatility',
  },
  [HEATMAP_MODES.CUSTOM_RISK]: {
    label: 'Combined Risk',
    description: 'Portfolio concentration + volatility + unrealized losses',
    category: 'risk',
    legendText: 'Considers position weight, volatility, and unrealized losses. Orange tint for elevated risk.',
    colorScheme: 'volatility',
  },
  };

export const HEATMAP_CATEGORIES = {
  concentration: { label: 'Concentration', modes: [HEATMAP_MODES.PORTFOLIO_WEIGHT, HEATMAP_MODES.ACCOUNT_WEIGHT] },
  daily: { label: 'Daily P&L', modes: [HEATMAP_MODES.DAILY_PNL_AMOUNT, HEATMAP_MODES.DAILY_PNL_PERCENT] },
  returns: { label: 'Returns & Gains', modes: [HEATMAP_MODES.UNREALIZED_GAIN_AMOUNT, HEATMAP_MODES.UNREALIZED_GAIN_PERCENT, HEATMAP_MODES.REALIZED_GAIN_AMOUNT, HEATMAP_MODES.REALIZED_GAIN_PERCENT, HEATMAP_MODES.REALIZED_GAIN_CONTRIBUTION, HEATMAP_MODES.TOTAL_RETURN, HEATMAP_MODES.PRICE_MOVEMENT] },
  risk: { label: 'Risk', modes: [HEATMAP_MODES.VOLATILITY, HEATMAP_MODES.CUSTOM_RISK] },
};