// ============================================================
// UNIFOLIO — Realized Positions Sample Data
// Structured so real brokerage transaction data can replace this later.
// Each entry represents a fully closed position (qty reduced to zero).
// ============================================================

export const rawRealizedPositions = [
  {
    id: 'r1',
    account_id: 'ibkr-tfsa',
    ticker: 'AAPL',
    name: 'Apple Inc',
    asset_class: 'Stock',
    sector: 'Technology',
    currency: 'USD',
    quantity: 5,
    average_buy_price: 168.40,
    average_sell_price: 220.50,
    total_cost_basis: 842.00,
    total_sale_value: 1102.50,
    realized_gain_loss_amount: 260.50,
    realized_gain_loss_percent: 30.94,
    open_date: '2023-09-15',
    close_date: '2026-04-28',
    holding_period_days: 956,
    position_status: 'Realized',
  },
  {
    id: 'r2',
    account_id: 'ibkr-margin',
    ticker: 'TSLA',
    name: 'Tesla Inc',
    asset_class: 'Stock',
    sector: 'Consumer Discretionary',
    currency: 'USD',
    quantity: 4,
    average_buy_price: 310.00,
    average_sell_price: 248.50,
    total_cost_basis: 1240.00,
    total_sale_value: 994.00,
    realized_gain_loss_amount: -246.00,
    realized_gain_loss_percent: -19.84,
    open_date: '2024-01-20',
    close_date: '2025-11-15',
    holding_period_days: 664,
    position_status: 'Realized',
  },
  {
    id: 'r3',
    account_id: 'ws-tfsa',
    ticker: 'AMZN',
    name: 'Amazon.com Inc',
    asset_class: 'Stock',
    sector: 'Consumer Discretionary',
    currency: 'USD',
    quantity: 3,
    average_buy_price: 142.80,
    average_sell_price: 191.20,
    total_cost_basis: 428.40,
    total_sale_value: 573.60,
    realized_gain_loss_amount: 145.20,
    realized_gain_loss_percent: 33.90,
    open_date: '2023-06-01',
    close_date: '2025-08-10',
    holding_period_days: 800,
    position_status: 'Realized',
  },
  {
    id: 'r4',
    account_id: 'ibkr-tfsa',
    ticker: 'META',
    name: 'Meta Platforms Inc',
    asset_class: 'Stock',
    sector: 'Technology',
    currency: 'USD',
    quantity: 2,
    average_buy_price: 380.50,
    average_sell_price: 512.00,
    total_cost_basis: 761.00,
    total_sale_value: 1024.00,
    realized_gain_loss_amount: 263.00,
    realized_gain_loss_percent: 34.56,
    open_date: '2024-02-10',
    close_date: '2025-09-22',
    holding_period_days: 589,
    position_status: 'Realized',
  },
  {
    id: 'r5',
    account_id: 'ibkr-margin',
    ticker: 'INTC',
    name: 'Intel Corp',
    asset_class: 'Stock',
    sector: 'Technology',
    currency: 'USD',
    quantity: 20,
    average_buy_price: 48.20,
    average_sell_price: 22.10,
    total_cost_basis: 964.00,
    total_sale_value: 442.00,
    realized_gain_loss_amount: -522.00,
    realized_gain_loss_percent: -54.15,
    open_date: '2023-04-12',
    close_date: '2025-06-05',
    holding_period_days: 784,
    position_status: 'Realized',
  },
  {
    id: 'r6',
    account_id: 'ws-rrsp',
    ticker: 'XIU.TO',
    name: 'iShares S&P/TSX 60 ETF',
    asset_class: 'ETF',
    sector: 'Index Fund',
    currency: 'CAD',
    quantity: 25,
    average_buy_price: 31.50,
    average_sell_price: 36.80,
    total_cost_basis: 787.50,
    total_sale_value: 920.00,
    realized_gain_loss_amount: 132.50,
    realized_gain_loss_percent: 16.83,
    open_date: '2023-10-05',
    close_date: '2025-04-20',
    holding_period_days: 562,
    position_status: 'Realized',
  },
  {
    id: 'r7',
    account_id: 'ibkr-tfsa',
    ticker: 'COIN',
    name: 'Coinbase Global Inc',
    asset_class: 'Stock',
    sector: 'Technology',
    currency: 'USD',
    quantity: 6,
    average_buy_price: 95.40,
    average_sell_price: 225.80,
    total_cost_basis: 572.40,
    total_sale_value: 1354.80,
    realized_gain_loss_amount: 782.40,
    realized_gain_loss_percent: 136.70,
    open_date: '2023-07-18',
    close_date: '2025-12-01',
    holding_period_days: 866,
    position_status: 'Realized',
  },
  {
    id: 'r8',
    account_id: 'ws-tfsa',
    ticker: 'BB.TO',
    name: 'BlackBerry Ltd',
    asset_class: 'Stock',
    sector: 'Technology',
    currency: 'CAD',
    quantity: 50,
    average_buy_price: 6.80,
    average_sell_price: 4.20,
    total_cost_basis: 340.00,
    total_sale_value: 210.00,
    realized_gain_loss_amount: -130.00,
    realized_gain_loss_percent: -38.24,
    open_date: '2024-03-01',
    close_date: '2025-10-14',
    holding_period_days: 592,
    position_status: 'Realized',
  },
  {
    id: 'r9',
    account_id: 'ibkr-margin',
    ticker: 'AMD',
    name: 'Advanced Micro Devices',
    asset_class: 'Stock',
    sector: 'Technology',
    currency: 'USD',
    quantity: 10,
    average_buy_price: 118.60,
    average_sell_price: 155.30,
    total_cost_basis: 1186.00,
    total_sale_value: 1553.00,
    realized_gain_loss_amount: 367.00,
    realized_gain_loss_percent: 30.94,
    open_date: '2024-05-20',
    close_date: '2026-01-08',
    holding_period_days: 598,
    position_status: 'Realized',
  },
  {
    id: 'r10',
    account_id: 'ws-fhsa',
    ticker: 'ZAG.TO',
    name: 'BMO Aggregate Bond Index ETF',
    asset_class: 'ETF',
    sector: 'Fixed Income',
    currency: 'CAD',
    quantity: 30,
    average_buy_price: 14.90,
    average_sell_price: 15.60,
    total_cost_basis: 447.00,
    total_sale_value: 468.00,
    realized_gain_loss_amount: 21.00,
    realized_gain_loss_percent: 4.70,
    open_date: '2025-01-10',
    close_date: '2025-12-22',
    holding_period_days: 346,
    position_status: 'Realized',
  },
  {
    id: 'r11',
    account_id: 'ibkr-rrsp',
    ticker: 'MRNA',
    name: 'Moderna Inc',
    asset_class: 'Stock',
    sector: 'Healthcare',
    currency: 'USD',
    quantity: 3,
    average_buy_price: 145.00,
    average_sell_price: 52.30,
    total_cost_basis: 435.00,
    total_sale_value: 156.90,
    realized_gain_loss_amount: -278.10,
    realized_gain_loss_percent: -63.93,
    open_date: '2023-11-08',
    close_date: '2025-07-30',
    holding_period_days: 629,
    position_status: 'Realized',
  },
  {
    id: 'r12',
    account_id: 'ibkr-margin',
    ticker: 'PLTR',
    name: 'Palantir Technologies',
    asset_class: 'Stock',
    sector: 'Technology',
    currency: 'USD',
    quantity: 15,
    average_buy_price: 18.40,
    average_sell_price: 72.60,
    total_cost_basis: 276.00,
    total_sale_value: 1089.00,
    realized_gain_loss_amount: 813.00,
    realized_gain_loss_percent: 294.57,
    open_date: '2023-08-15',
    close_date: '2026-02-14',
    holding_period_days: 913,
    position_status: 'Realized',
  },
];

// ─── SUMMARY CALCULATIONS ─────────────────────────────────────

export function calcRealizedSummary(positions) {
  if (!positions.length) return {
    total_gains: 0, total_losses: 0, net_pnl: 0,
    best_trade: null, worst_trade: null,
    avg_return_pct: 0, position_count: 0,
  };

  let total_gains = 0, total_losses = 0;
  positions.forEach(p => {
    if (p.realized_gain_loss_amount > 0) total_gains += p.realized_gain_loss_amount;
    else total_losses += p.realized_gain_loss_amount;
  });

  const sorted_by_pnl = [...positions].sort((a, b) => b.realized_gain_loss_amount - a.realized_gain_loss_amount);
  const avg_return_pct = positions.reduce((s, p) => s + p.realized_gain_loss_percent, 0) / positions.length;

  return {
    total_gains,
    total_losses,
    net_pnl: total_gains + total_losses,
    best_trade: sorted_by_pnl[0] ?? null,
    worst_trade: sorted_by_pnl[sorted_by_pnl.length - 1] ?? null,
    avg_return_pct: Math.round(avg_return_pct * 100) / 100,
    position_count: positions.length,
  };
}

// ─── DATE RANGE FILTER ────────────────────────────────────────

export function filterRealizedByDateRange(positions, startDate, endDate) {
  if (!startDate && !endDate) return positions;
  return positions.filter(p => {
    const close = new Date(p.close_date);
    if (startDate && close < new Date(startDate)) return false;
    if (endDate && close > new Date(endDate)) return false;
    return true;
  });
}