// ============================================================
// UNIFOLIO — Structured Sample Data
// This file contains all raw sample data.
// Nothing calculated here — all derived values come from portfolioEngine.js
// CLEARLY LABELED AS SAMPLE DATA
// ============================================================

export const DATA_IS_SAMPLE = true;
export const SAMPLE_DATA_LABEL = 'Sample Data';

// ─── INSTITUTIONS ─────────────────────────────────────────────
export const institutions = [
  {
    id: 'ws',
    name: 'Wealthsimple',
    type: 'Brokerage',
    country: 'CA',
    logo: 'wealthsimple',
    color: '#00c853',
    connection_status: 'connected',
    last_sync_time: '2026-05-05T14:30:00Z',
    api_supported: true,
    notes: 'Connected via sample data',
  },
  {
    id: 'ibkr',
    name: 'Interactive Brokers',
    type: 'Brokerage',
    country: 'US',
    logo: 'interactive-brokers',
    color: '#e53935',
    connection_status: 'connected',
    last_sync_time: '2026-05-05T14:25:00Z',
    api_supported: true,
    notes: 'Connected via sample data',
  },
  {
    id: 'qt',
    name: 'Questrade',
    type: 'Brokerage',
    country: 'CA',
    logo: 'questrade',
    color: '#ffc107',
    connection_status: 'disconnected',
    last_sync_time: null,
    api_supported: true,
    notes: '',
  },
  {
    id: 'td',
    name: 'TD Direct Investing',
    type: 'Bank',
    country: 'CA',
    logo: 'td',
    color: '#34a853',
    connection_status: 'not_connected',
    last_sync_time: null,
    api_supported: false,
    notes: '',
  },
  {
    id: 'rbc',
    name: 'RBC Direct Investing',
    type: 'Bank',
    country: 'CA',
    logo: 'rbc',
    color: '#1565c0',
    connection_status: 'not_connected',
    last_sync_time: null,
    api_supported: false,
    notes: '',
  },
  {
    id: 'bmo',
    name: 'BMO InvestorLine',
    type: 'Bank',
    country: 'CA',
    logo: 'bmo',
    color: '#0d47a1',
    connection_status: 'not_connected',
    last_sync_time: null,
    api_supported: false,
    notes: '',
  },
  {
    id: 'scotia',
    name: 'Scotia iTRADE',
    type: 'Bank',
    country: 'CA',
    logo: 'scotia',
    color: '#c62828',
    connection_status: 'not_connected',
    last_sync_time: null,
    api_supported: false,
    notes: '',
  },
  {
    id: 'cibc',
    name: "CIBC Investor's Edge",
    type: 'Bank',
    country: 'CA',
    logo: 'cibc',
    color: '#b71c1c',
    connection_status: 'not_connected',
    last_sync_time: null,
    api_supported: false,
    notes: '',
  },
  {
    id: 'nb',
    name: 'National Bank Direct',
    type: 'Bank',
    country: 'CA',
    logo: 'national-bank',
    color: '#d32f2f',
    connection_status: 'not_connected',
    last_sync_time: null,
    api_supported: false,
    notes: '',
  },
  {
    id: 'schwab',
    name: 'Charles Schwab',
    type: 'Brokerage',
    country: 'US',
    logo: 'schwab',
    color: '#1976d2',
    connection_status: 'connected',
    last_sync_time: '2026-05-05T13:45:00Z',
    api_supported: true,
    notes: 'US brokerage account',
  },
  {
    id: 'chase',
    name: 'Chase Bank',
    type: 'Bank',
    country: 'US',
    logo: 'chase',
    color: '#117dba',
    connection_status: 'not_connected',
    last_sync_time: null,
    api_supported: false,
    notes: '',
  },
  ];

// ─── ACCOUNT TYPES ────────────────────────────────────────────
export const accountTypes = ['TFSA', 'RRSP', 'FHSA', 'Cash', 'Margin', 'Corporate', 'Crypto', 'Savings', 'Other'];

// ─── ACCOUNTS ─────────────────────────────────────────────────
// Only raw stored fields. All calculated values come from portfolioEngine.
export const accounts = [
  {
    id: 'ws-tfsa',
    institution_id: 'ws',
    account_name: 'TFSA',
    account_type: 'TFSA',
    base_currency: 'CAD',
    cash_balance: 1250.00,
    included_in_portfolio: true,
    last_updated: '2026-05-05T14:30:00Z',
  },
  {
    id: 'ws-rrsp',
    institution_id: 'ws',
    account_name: 'RRSP',
    account_type: 'RRSP',
    base_currency: 'CAD',
    cash_balance: 800.00,
    included_in_portfolio: true,
    last_updated: '2026-05-05T14:30:00Z',
  },
  {
    id: 'ws-crypto',
    institution_id: 'ws',
    account_name: 'Crypto',
    account_type: 'Crypto',
    base_currency: 'CAD',
    cash_balance: 200.00,
    included_in_portfolio: true,
    last_updated: '2026-05-05T14:30:00Z',
  },
  {
    id: 'ws-fhsa',
    institution_id: 'ws',
    account_name: 'FHSA',
    account_type: 'FHSA',
    base_currency: 'CAD',
    cash_balance: 500.00,
    included_in_portfolio: true,
    last_updated: '2026-05-05T14:30:00Z',
  },
  {
    id: 'ibkr-tfsa',
    institution_id: 'ibkr',
    account_name: 'TFSA',
    account_type: 'TFSA',
    base_currency: 'USD',
    cash_balance: 2100.00,
    included_in_portfolio: true,
    last_updated: '2026-05-05T14:25:00Z',
  },
  {
    id: 'ibkr-margin',
    institution_id: 'ibkr',
    account_name: 'Margin',
    account_type: 'Margin',
    base_currency: 'USD',
    cash_balance: 5400.00,
    included_in_portfolio: true,
    last_updated: '2026-05-05T14:25:00Z',
  },
  {
    id: 'ibkr-rrsp',
    institution_id: 'ibkr',
    account_name: 'RRSP',
    account_type: 'RRSP',
    base_currency: 'USD',
    cash_balance: 750.00,
    included_in_portfolio: true,
    last_updated: '2026-05-05T14:25:00Z',
  },
  {
    id: 'schwab-brokerage',
    institution_id: 'schwab',
    account_name: 'US Brokerage',
    account_type: 'Cash',
    base_currency: 'USD',
    cash_balance: 3500.00,
    included_in_portfolio: true,
    last_updated: '2026-05-05T13:45:00Z',
  },
  {
    id: 'chase-checking',
    institution_id: 'chase',
    account_name: 'Checking',
    account_type: 'Savings',
    base_currency: 'USD',
    cash_balance: 8200.00,
    included_in_portfolio: false,
    last_updated: null,
  },
  ];

  // ─── PREDICTION MARKET ACCOUNTS ────────────────────────────────
  export const predictionMarketAccounts = [
  {
   id: 'pm-polymarket',
   platform: 'Polymarket',
   account_name: 'Polymarket Trading',
   cash_balance: 2500.00,
   total_position_value: 1840.50,
   total_account_value: 4340.50,
   currency: 'USD',
   connection_status: 'Manual',
   included_in_net_value: true,
   last_synced: '2026-05-05T10:30:00Z',
  },
  {
   id: 'pm-kalshi',
   platform: 'Kalshi',
   account_name: 'Kalshi Events',
   cash_balance: 1200.00,
   total_position_value: 650.25,
   total_account_value: 1850.25,
   currency: 'USD',
   connection_status: 'Manual',
   included_in_net_value: true,
   last_synced: '2026-05-05T09:15:00Z',
  },
  ];

  // ─── PREDICTION MARKET POSITIONS ──────────────────────────────
  export const predictionMarketPositions = [
  {
   id: 'pmp1',
   platform: 'Polymarket',
   account_id: 'pm-polymarket',
   market_id: 'poly-eth-mainnet-2026',
   market_title: 'Will Ethereum be above $4,000 by Dec 2026?',
   outcome: 'Yes',
   position_type: 'Long',
   quantity: 200,
   average_price: 0.58,
   current_price: 0.62,
   current_market_value: 124.00,
   cost_basis: 116.00,
   unrealized_gain_loss: 8.00,
   probability: 62,
   market_close_date: '2026-12-31',
   status: 'Open',
   currency: 'USD',
  },
  {
   id: 'pmp2',
   platform: 'Polymarket',
   account_id: 'pm-polymarket',
   market_id: 'poly-btc-halvings-2026',
   market_title: 'Bitcoin BTC to $100k by mid-2026?',
   outcome: 'No',
   position_type: 'Short',
   quantity: 150,
   average_price: 0.42,
   current_price: 0.38,
   current_market_value: 57.00,
   cost_basis: 63.00,
   unrealized_gain_loss: 6.00,
   probability: 38,
   market_close_date: '2026-06-30',
   status: 'Open',
   currency: 'USD',
  },
  {
   id: 'pmp3',
   platform: 'Polymarket',
   account_id: 'pm-polymarket',
   market_id: 'poly-sp500-rally-2026',
   market_title: 'S&P 500 above 6,500 by year-end?',
   outcome: 'Yes',
   position_type: 'Long',
   quantity: 180,
   average_price: 0.65,
   current_price: 0.71,
   current_market_value: 127.80,
   cost_basis: 117.00,
   unrealized_gain_loss: 10.80,
   probability: 71,
   market_close_date: '2026-12-31',
   status: 'Open',
   currency: 'USD',
  },
  {
   id: 'pmp4',
   platform: 'Polymarket',
   account_id: 'pm-polymarket',
   market_id: 'poly-fed-rates-2026',
   market_title: 'US Fed Rate > 4% by end of Q3 2026?',
   outcome: 'No',
   position_type: 'Long',
   quantity: 280,
   average_price: 0.75,
   current_price: 0.73,
   current_market_value: 204.40,
   cost_basis: 210.00,
   unrealized_gain_loss: -5.60,
   probability: 27,
   market_close_date: '2026-09-30',
   status: 'Open',
   currency: 'USD',
  },
  {
   id: 'pmk1',
   platform: 'Kalshi',
   account_id: 'pm-kalshi',
   market_id: 'kalshi-unemployment-2026',
   market_title: 'US Unemployment above 5% in June 2026?',
   outcome: 'No',
   position_type: 'Long',
   quantity: 120,
   average_price: 0.45,
   current_price: 0.48,
   current_market_value: 57.60,
   cost_basis: 54.00,
   unrealized_gain_loss: 3.60,
   probability: 48,
   market_close_date: '2026-06-30',
   status: 'Open',
   currency: 'USD',
  },
  {
   id: 'pmk2',
   platform: 'Kalshi',
   account_id: 'pm-kalshi',
   market_id: 'kalshi-oil-price-2026',
   market_title: 'Brent Oil above $90/barrel by Q4?',
   outcome: 'Yes',
   position_type: 'Long',
   quantity: 200,
   average_price: 0.55,
   current_price: 0.52,
   current_market_value: 104.00,
   cost_basis: 110.00,
   unrealized_gain_loss: -6.00,
   probability: 52,
   market_close_date: '2026-12-31',
   status: 'Open',
   currency: 'USD',
  },
  {
   id: 'pmk3',
   platform: 'Kalshi',
   account_id: 'pm-kalshi',
   market_id: 'kalshi-election-result-2026',
   market_title: 'Democratic party wins 2026 midterms?',
   outcome: 'Yes',
   position_type: 'Long',
   quantity: 100,
   average_price: 0.52,
   current_price: 0.48,
   current_market_value: 48.00,
   cost_basis: 52.00,
   unrealized_gain_loss: -4.00,
   probability: 48,
   market_close_date: '2026-11-03',
   status: 'Open',
   currency: 'USD',
  },
  // Closed/settled position for reference
  {
   id: 'pmc1',
   platform: 'Polymarket',
   account_id: 'pm-polymarket',
   market_id: 'poly-btc-rally-2025',
   market_title: 'Bitcoin above $100k by Dec 2025?',
   outcome: 'Yes',
   position_type: 'Long',
   quantity: 250,
   average_price: 0.35,
   current_price: 0.95,
   current_market_value: 237.50,
   cost_basis: 87.50,
   unrealized_gain_loss: 150.00,
   realized_gain_loss: 150.00,
   probability: 95,
   market_close_date: '2025-12-31',
   status: 'Settled',
   currency: 'USD',
  },
  ];

// ─── ASSETS ───────────────────────────────────────────────────
// Master asset catalogue. Prices are the source of truth for all calculations.
export const assets = {
  'TTWO': {
    ticker: 'TTWO', name: 'Take-Two Interactive Software Inc',
    asset_class: 'Stock', sector: 'Technology', industry: 'Interactive Entertainment',
    country: 'US', currency: 'USD', exchange: 'NASDAQ',
    current_price: 223.01, previous_close: 226.08,
    market_cap: 34_200_000_000, volume: 1_230_000,
    fifty_two_week_high: 242.00, fifty_two_week_low: 120.50,
  },
  'VOO': {
    ticker: 'VOO', name: 'Vanguard S&P 500 ETF',
    asset_class: 'ETF', sector: 'Index Fund', industry: 'Large-Cap Blend',
    country: 'US', currency: 'USD', exchange: 'NYSE',
    current_price: 666.00, previous_close: 659.75,
    market_cap: null, volume: 4_500_000,
    fifty_two_week_high: 700.00, fifty_two_week_low: 480.00,
  },
  'MSFT': {
    ticker: 'MSFT', name: 'Microsoft Corp',
    asset_class: 'Stock', sector: 'Technology', industry: 'Software',
    country: 'US', currency: 'USD', exchange: 'NASDAQ',
    current_price: 410.57, previous_close: 413.57,
    market_cap: 3_050_000_000_000, volume: 22_000_000,
    fifty_two_week_high: 465.00, fifty_two_week_low: 360.00,
  },
  'ELDN': {
    ticker: 'ELDN', name: 'Eledon Pharmaceuticals Inc',
    asset_class: 'Stock', sector: 'Healthcare', industry: 'Biotechnology',
    country: 'US', currency: 'USD', exchange: 'NASDAQ',
    current_price: 3.78, previous_close: 3.74,
    market_cap: 42_000_000, volume: 180_000,
    fifty_two_week_high: 8.20, fifty_two_week_low: 1.90,
  },
  'ITGR': {
    ticker: 'ITGR', name: 'Integer Holdings Corp',
    asset_class: 'Stock', sector: 'Healthcare', industry: 'Medical Devices',
    country: 'US', currency: 'USD', exchange: 'NYSE',
    current_price: 85.87, previous_close: 85.00,
    market_cap: 2_800_000_000, volume: 210_000,
    fifty_two_week_high: 105.00, fifty_two_week_low: 68.00,
  },
  'NVDA': {
    ticker: 'NVDA', name: 'NVIDIA Corp',
    asset_class: 'Stock', sector: 'Technology', industry: 'Semiconductors',
    country: 'US', currency: 'USD', exchange: 'NASDAQ',
    current_price: 196.85, previous_close: 200.85,
    market_cap: 4_800_000_000_000, volume: 285_000_000,
    fifty_two_week_high: 220.00, fifty_two_week_low: 76.00,
  },
  'LULU': {
    ticker: 'LULU', name: 'Lululemon Athletica Inc',
    asset_class: 'Stock', sector: 'Consumer Discretionary', industry: 'Apparel & Footwear',
    country: 'CA', currency: 'USD', exchange: 'NASDAQ',
    current_price: 130.23, previous_close: 127.83,
    market_cap: 16_800_000_000, volume: 3_200_000,
    fifty_two_week_high: 190.00, fifty_two_week_low: 108.00,
  },
  'LLY': {
    ticker: 'LLY', name: 'Eli Lilly & Co',
    asset_class: 'Stock', sector: 'Healthcare', industry: 'Pharmaceuticals',
    country: 'US', currency: 'USD', exchange: 'NYSE',
    current_price: 985.06, previous_close: 937.06,
    market_cap: 940_000_000_000, volume: 2_800_000,
    fifty_two_week_high: 1050.00, fifty_two_week_low: 740.00,
  },
  'VFV.TO': {
    ticker: 'VFV.TO', name: 'Vanguard S&P 500 Index ETF',
    asset_class: 'ETF', sector: 'Index Fund', industry: 'Large-Cap Blend',
    country: 'CA', currency: 'CAD', exchange: 'TSX',
    current_price: 175.46, previous_close: 174.71,
    market_cap: null, volume: 850_000,
    fifty_two_week_high: 190.00, fifty_two_week_low: 140.00,
  },
  'NVO': {
    ticker: 'NVO', name: 'Novo Nordisk A/S ADR',
    asset_class: 'Stock', sector: 'Healthcare', industry: 'Pharmaceuticals',
    country: 'DK', currency: 'USD', exchange: 'NYSE',
    current_price: 45.17, previous_close: 44.64,
    market_cap: 199_000_000_000, volume: 4_100_000,
    fifty_two_week_high: 69.00, fifty_two_week_low: 38.00,
  },
  'SPRX': {
    ticker: 'SPRX', name: 'Spear Alpha ETF',
    asset_class: 'ETF', sector: 'Technology', industry: 'Thematic Growth',
    country: 'US', currency: 'USD', exchange: 'NASDAQ',
    current_price: 44.26, previous_close: 43.66,
    market_cap: null, volume: 95_000,
    fifty_two_week_high: 52.00, fifty_two_week_low: 30.00,
  },
  'IBIT': {
    ticker: 'IBIT', name: 'iShares Bitcoin Trust ETF',
    asset_class: 'ETF', sector: 'Crypto', industry: 'Digital Assets',
    country: 'US', currency: 'USD', exchange: 'NASDAQ',
    current_price: 46.28, previous_close: 45.84,
    market_cap: null, volume: 38_000_000,
    fifty_two_week_high: 58.00, fifty_two_week_low: 24.00,
  },
  'AAPL': {
    ticker: 'AAPL', name: 'Apple Inc',
    asset_class: 'Stock', sector: 'Technology', industry: 'Consumer Electronics',
    country: 'US', currency: 'USD', exchange: 'NASDAQ',
    current_price: 218.45, previous_close: 220.45,
    market_cap: 3_340_000_000_000, volume: 56_000_000,
    fifty_two_week_high: 245.00, fifty_two_week_low: 165.00,
  },
  'SHOP.TO': {
    ticker: 'SHOP.TO', name: 'Shopify Inc',
    asset_class: 'Stock', sector: 'Technology', industry: 'E-Commerce Software',
    country: 'CA', currency: 'CAD', exchange: 'TSX',
    current_price: 142.80, previous_close: 140.60,
    market_cap: 185_000_000_000, volume: 2_100_000,
    fifty_two_week_high: 165.00, fifty_two_week_low: 100.00,
  },
};

// ─── RAW HOLDINGS ─────────────────────────────────────────────
// Only raw stored fields. Computed fields (market value, P&L, etc.)
// are derived in portfolioEngine.js
export const rawHoldings = [
  {
    id: 'h1', account_id: 'ibkr-tfsa', ticker: 'TTWO',
    quantity: 17, average_price: 231.02, realized_gain_loss_amount: -151,
    purchase_history: [
      { date: '2025-08-15', qty: 10, price: 238.50 },
      { date: '2025-11-02', qty: 5,  price: 220.00 },
      { date: '2026-02-10', qty: 2,  price: 225.30 },
    ],
  },
  {
    id: 'h2', account_id: 'ibkr-tfsa', ticker: 'VOO',
    quantity: 4, average_price: 616.24, realized_gain_loss_amount: 201,
    purchase_history: [
      { date: '2024-06-01', qty: 2, price: 580.00 },
      { date: '2025-01-15', qty: 1, price: 620.00 },
      { date: '2025-09-20', qty: 1, price: 665.00 },
    ],
  },
  {
    id: 'h3', account_id: 'ibkr-tfsa', ticker: 'MSFT',
    quantity: 2, average_price: 399.50, realized_gain_loss_amount: 22,
    purchase_history: [{ date: '2025-03-10', qty: 2, price: 399.50 }],
  },
  {
    id: 'h4', account_id: 'ws-tfsa', ticker: 'ELDN',
    quantity: 100, average_price: 4.16, realized_gain_loss_amount: -34,
    purchase_history: [{ date: '2025-12-01', qty: 100, price: 4.16 }],
  },
  {
    // Zero quantity — excluded from all allocation calculations
    id: 'h5', account_id: 'ws-tfsa', ticker: 'ITGR',
    quantity: 0, average_price: 0, realized_gain_loss_amount: 0,
    purchase_history: [],
  },
  {
    id: 'h6', account_id: 'ibkr-margin', ticker: 'NVDA',
    quantity: 8, average_price: 142.30, realized_gain_loss_amount: 520,
    purchase_history: [
      { date: '2024-03-15', qty: 5, price: 120.00 },
      { date: '2024-11-20', qty: 3, price: 179.50 },
    ],
  },
  {
    id: 'h7', account_id: 'ws-tfsa', ticker: 'LULU',
    quantity: 5, average_price: 118.60, realized_gain_loss_amount: 0,
    purchase_history: [{ date: '2025-06-01', qty: 5, price: 118.60 }],
  },
  {
    id: 'h8', account_id: 'ibkr-rrsp', ticker: 'LLY',
    quantity: 1, average_price: 820.00, realized_gain_loss_amount: 0,
    purchase_history: [{ date: '2025-01-10', qty: 1, price: 820.00 }],
  },
  {
    id: 'h9', account_id: 'ws-rrsp', ticker: 'VFV.TO',
    quantity: 20, average_price: 158.20, realized_gain_loss_amount: 85,
    purchase_history: [
      { date: '2024-01-15', qty: 10, price: 145.00 },
      { date: '2024-07-20', qty: 5,  price: 160.00 },
      { date: '2025-04-10', qty: 5,  price: 170.00 },
    ],
  },
  {
    id: 'h10', account_id: 'ws-fhsa', ticker: 'NVO',
    quantity: 15, average_price: 52.30, realized_gain_loss_amount: -45,
    purchase_history: [{ date: '2025-07-01', qty: 15, price: 52.30 }],
  },
  {
    id: 'h11', account_id: 'ibkr-margin', ticker: 'SPRX',
    quantity: 30, average_price: 38.50, realized_gain_loss_amount: 0,
    purchase_history: [{ date: '2025-05-15', qty: 30, price: 38.50 }],
  },
  {
    // Only crypto holding — must show 100% of crypto allocation
    id: 'h12', account_id: 'ws-crypto', ticker: 'IBIT',
    quantity: 50, average_price: 39.80, realized_gain_loss_amount: 120,
    purchase_history: [
      { date: '2024-04-01', qty: 25, price: 35.00 },
      { date: '2024-10-15', qty: 25, price: 44.60 },
    ],
  },
  {
    id: 'h13', account_id: 'ibkr-tfsa', ticker: 'AAPL',
    quantity: 3, average_price: 195.20, realized_gain_loss_amount: 150,
    purchase_history: [{ date: '2024-09-01', qty: 3, price: 195.20 }],
  },
  {
    id: 'h14', account_id: 'ws-tfsa', ticker: 'SHOP.TO',
    quantity: 10, average_price: 98.50, realized_gain_loss_amount: 280,
    purchase_history: [{ date: '2023-11-01', qty: 10, price: 98.50 }],
  },
  {
    id: 'h15', account_id: 'schwab-brokerage', ticker: 'AAPL',
    quantity: 15, average_price: 180.00, realized_gain_loss_amount: 580,
    purchase_history: [
      { date: '2024-06-10', qty: 10, price: 175.00 },
      { date: '2025-02-15', qty: 5,  price: 190.00 },
    ],
  },
  {
    id: 'h16', account_id: 'schwab-brokerage', ticker: 'VOO',
    quantity: 12, average_price: 640.00, realized_gain_loss_amount: 315,
    purchase_history: [
      { date: '2023-12-01', qty: 8, price: 620.00 },
      { date: '2025-03-20', qty: 4, price: 670.00 },
    ],
  },
  ];

// ─── TRANSACTIONS ─────────────────────────────────────────────
export const transactions = [
  { id: 't1',  date: '2026-05-05', transaction_type: 'Buy',                 ticker: 'NVDA',    quantity: 2,   price: 196.85, total_amount: 393.70,  account_id: 'ibkr-margin', currency: 'USD', notes: '' },
  { id: 't2',  date: '2026-05-04', transaction_type: 'Sell',                ticker: 'TTWO',    quantity: 3,   price: 225.10, total_amount: 675.30,  account_id: 'ibkr-tfsa',  currency: 'USD', notes: '' },
  { id: 't3',  date: '2026-05-03', transaction_type: 'Dividend',            ticker: 'VOO',     quantity: 0,   price: 0,      total_amount: 12.45,   account_id: 'ibkr-tfsa',  currency: 'USD', notes: 'Q1 dividend' },
  { id: 't4',  date: '2026-05-02', transaction_type: 'Buy',                 ticker: 'LULU',    quantity: 5,   price: 118.60, total_amount: 593.00,  account_id: 'ws-tfsa',    currency: 'USD', notes: '' },
  { id: 't5',  date: '2026-05-01', transaction_type: 'Deposit',             ticker: '',        quantity: 0,   price: 0,      total_amount: 5000.00, account_id: 'ws-rrsp',    currency: 'CAD', notes: 'Annual RRSP contribution' },
  { id: 't6',  date: '2026-04-30', transaction_type: 'Buy',                 ticker: 'VFV.TO',  quantity: 5,   price: 170.00, total_amount: 850.00,  account_id: 'ws-rrsp',    currency: 'CAD', notes: '' },
  { id: 't7',  date: '2026-04-28', transaction_type: 'Sell',                ticker: 'AAPL',    quantity: 2,   price: 220.50, total_amount: 441.00,  account_id: 'ibkr-tfsa',  currency: 'USD', notes: '' },
  { id: 't8',  date: '2026-04-25', transaction_type: 'Dividend',            ticker: 'MSFT',    quantity: 0,   price: 0,      total_amount: 3.78,    account_id: 'ibkr-tfsa',  currency: 'USD', notes: '' },
  { id: 't9',  date: '2026-04-22', transaction_type: 'Buy',                 ticker: 'IBIT',    quantity: 10,  price: 44.60,  total_amount: 446.00,  account_id: 'ws-crypto',  currency: 'USD', notes: '' },
  { id: 't10', date: '2026-04-20', transaction_type: 'Withdrawal',          ticker: '',        quantity: 0,   price: 0,      total_amount: 2000.00, account_id: 'ibkr-margin', currency: 'USD', notes: '' },
  { id: 't11', date: '2026-04-18', transaction_type: 'Transfer',            ticker: '',        quantity: 0,   price: 0,      total_amount: 3000.00, account_id: 'ws-tfsa',    currency: 'CAD', notes: 'TFSA transfer in' },
  { id: 't12', date: '2026-04-15', transaction_type: 'Buy',                 ticker: 'NVO',     quantity: 15,  price: 52.30,  total_amount: 784.50,  account_id: 'ws-fhsa',    currency: 'USD', notes: '' },
  { id: 't13', date: '2026-04-10', transaction_type: 'Fee',                 ticker: '',        quantity: 0,   price: 0,      total_amount: 9.95,    account_id: 'ibkr-margin', currency: 'USD', notes: 'Platform fee' },
  { id: 't14', date: '2026-04-05', transaction_type: 'Currency Conversion', ticker: 'USD/CAD', quantity: 0,   price: 1.38,   total_amount: 5000.00, account_id: 'ws-tfsa',    currency: 'CAD', notes: 'FX conversion' },
  { id: 't15', date: '2026-03-28', transaction_type: 'Buy',                 ticker: 'SPRX',    quantity: 30,  price: 38.50,  total_amount: 1155.00, account_id: 'ibkr-margin', currency: 'USD', notes: '' },
  { id: 't16', date: '2026-03-15', transaction_type: 'Deposit',             ticker: '',        quantity: 0,   price: 0,      total_amount: 2500.00, account_id: 'ibkr-tfsa',  currency: 'USD', notes: 'TFSA contribution' },
  { id: 't17', date: '2026-03-01', transaction_type: 'Stock Split',         ticker: 'NVDA',    quantity: 10,  price: 0,      total_amount: 0,       account_id: 'ibkr-margin', currency: 'USD', notes: '10:1 split (historical)' },
  { id: 't18', date: '2026-02-20', transaction_type: 'Interest',            ticker: '',        quantity: 0,   price: 0,      total_amount: 18.40,   account_id: 'ibkr-margin', currency: 'USD', notes: 'Cash interest' },
];

// ─── BENCHMARKS ───────────────────────────────────────────────
export const benchmarks = [
  { id: 'spx',  benchmark_name: 'S&P 500',                    symbol: 'SPX',  category: 'Index',   current_value: 5600.00, performance_percent: 14.2 },
  { id: 'ndx',  benchmark_name: 'NASDAQ-100',                 symbol: 'NDX',  category: 'Index',   current_value: 19800.00, performance_percent: 18.6 },
  { id: 'dji',  benchmark_name: 'Dow Jones Industrial Avg',   symbol: 'DJIA', category: 'Index',   current_value: 42000.00, performance_percent: 9.8 },
  { id: 'rut',  benchmark_name: 'Russell 2000',               symbol: 'RUT',  category: 'Index',   current_value: 2100.00,  performance_percent: 6.1 },
  { id: 'btc',  benchmark_name: 'Bitcoin',                    symbol: 'BTC',  category: 'Crypto',  current_value: 97500.00, performance_percent: 42.0 },
  { id: 'gold', benchmark_name: 'Gold',                       symbol: 'GOLD', category: 'Commodity',current_value: 3320.00, performance_percent: 28.5 },
  { id: 'vtsa', benchmark_name: 'US Total Market',            symbol: 'VTI',  category: 'Index',   current_value: 280.00,   performance_percent: 13.4 },
  { id: 'xcad', benchmark_name: 'Canadian Total Market',      symbol: 'XIC',  category: 'Index',   current_value: 38.50,    performance_percent: 7.8 },
];

// ─── WATCHLIST ────────────────────────────────────────────────
export const watchlist = [
  { id: 'w1', ticker: 'AMZN', name: 'Amazon.com Inc',         last_price: 198.45, daily_change: 2.15,  daily_change_pct: 1.09,  target_price: 210.00, notes: 'Watching for pullback below $190' },
  { id: 'w2', ticker: 'GOOG', name: 'Alphabet Inc',           last_price: 178.90, daily_change: -1.30, daily_change_pct: -0.72, target_price: 185.00, notes: 'AI catalysts upcoming' },
  { id: 'w3', ticker: 'TSLA', name: 'Tesla Inc',              last_price: 285.60, daily_change: 8.40,  daily_change_pct: 3.03,  target_price: 250.00, notes: 'Too expensive, wait for dip' },
  { id: 'w4', ticker: 'META', name: 'Meta Platforms Inc',     last_price: 525.30, daily_change: 3.20,  daily_change_pct: 0.61,  target_price: 500.00, notes: 'Strong Reels monetization' },
  { id: 'w5', ticker: 'AMD',  name: 'Advanced Micro Devices', last_price: 162.75, daily_change: -2.80, daily_change_pct: -1.69, target_price: 150.00, notes: 'Wait for next earnings' },
  { id: 'w6', ticker: 'COST', name: 'Costco Wholesale Corp',  last_price: 945.20, daily_change: 5.10,  daily_change_pct: 0.54,  target_price: 900.00, notes: 'Dividend play' },
];
